name: user_location_processing
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - arrow-cpp=0.15.1
  - async_generator=1.10
  - attrs=20.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - boost-cpp=1.67.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - colorama=0.4.3
  - console_shortcut=0.1.1
  - cryptography=3.1.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - double-conversion=3.1.5
  - entrypoints=0.3
  - gflags=2.2.2
  - glog=0.4.0
  - grpc-cpp=1.26.0
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab=2.2.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - libboost=1.67.0
  - libprotobuf=3.11.2
  - libsodium=1.0.18
  - lz4-c=1.8.1.2
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - nbclient=0.5.0
  - nbconvert=6.0.6
  - nbformat=5.0.7
  - nest-asyncio=1.4.1
  - notebook=6.1.4
  - numpy=1.19.1
  - numpy-base=1.19.1
  - openssl=1.1.1h
  - packaging=20.4
  - pandas=1.1.2
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pickleshare=0.7.5
  - pip=20.2.3
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - py4j=0.10.9
  - pyarrow=0.15.1
  - pycparser=2.20
  - pydeck=0.4.1
  - pygments=2.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pyspark=3.0.0
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyzmq=19.0.2
  - re2=2019.08.01
  - requests=2.24.0
  - scipy=1.5.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.33.0
  - terminado=0.8.3
  - testpath=0.4.4
  - thrift-cpp=0.11.0
  - tornado=6.0.4
  - traitlets=5.0.4
  - uriparser=0.9.3
  - urllib3=1.25.10
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
